#!/usr/bin/env bash
# Bản Linux của build_and_flash.bat: build bằng CMake/Ninja rồi nạp firmware
# lên STM32F103C8T6 qua ST-Link bằng st-flash.
set -e

cd "$(dirname "${BASH_SOURCE[0]}")"

FLASH_ADDR=0x08000000

# =============================================================================
# STEP 1: CONFIGURING PROJECT WITH CMAKE (chỉ chạy khi build/ chưa có sẵn)
# =============================================================================
if [ ! -f build/build.ninja ]; then
    echo "STEP 1: CONFIGURING PROJECT WITH CMAKE"
    cmake -G Ninja -B build
    echo
fi

# =============================================================================
# STEP 2: COMPILING FIRMWARE WITH NINJA (incremental — chỉ build lại file đã đổi)
# =============================================================================
echo "STEP 2: COMPILING FIRMWARE WITH NINJA"
ninja -C build

FOUND_BIN=$(find build -maxdepth 1 -name '*.bin' | head -n1)
if [ -z "$FOUND_BIN" ]; then
    echo "[ERROR] No .bin file generated by Ninja!"
    exit 1
fi
echo "Firmware binary: $FOUND_BIN"
echo

# =============================================================================
# STEP 3: FLASHING FIRMWARE TO TARGET MCU
# =============================================================================
echo "STEP 3: FLASHING FIRMWARE TO TARGET MCU"
if ! command -v st-flash >/dev/null 2>&1; then
    echo "[ERROR] st-flash not found. Install stlink-tools (e.g. apt install stlink-tools)."
    exit 1
fi

st-flash write "$FOUND_BIN" "$FLASH_ADDR"
st-flash reset

echo
echo "==================================================="
echo "[SUCCESS] Congratulations! System running smoothly."
echo "==================================================="
