@echo off
setlocal enabledelayedexpansion

:: =============================================================================
:: STEP 1: CLEANING BUILD DIRECTORY
:: =============================================================================
rem Bước này tiến hành kiểm tra sự tồn tại của thư mục build cũ.
rem Nếu tìm thấy, script sẽ xóa toàn bộ thư mục này cùng các file rác bên trong
rem nhằm đảm bảo quá trình biên dịch mới hoàn toàn sạch sẽ, không bị xung đột.
echo STEP 1: CLEANING BUILD DIRECTORY
echo Deleting existing build folder...
if exist build (
    rmdir /s /q build
)
echo.

:: =============================================================================
:: STEP 2: CONFIGURING PROJECT WITH CMAKE
:: =============================================================================
rem Bước này gọi công cụ CMake để quét file cấu hình CMakeLists.txt của dự án.
rem Tham số -G "Ninja" chỉ định sử dụng bộ sinh (Generator) là Ninja.
rem Tham số -B build chỉ định xuất các file cấu hình vào thư mục build/.
echo STEP 2: CONFIGURING PROJECT WITH CMAKE
cmake -G "Ninja" -B build
if %errorlevel% neq 0 (
    echo [ERROR] CMake configuration failed!
    pause
    exit /b %errorlevel%
)
echo.

:: =============================================================================
:: STEP 3: COMPILING FIRMWARE WITH NINJA
:: =============================================================================
rem Bước này kích hoạt trực tiếp công cụ điều phối biên dịch Ninja bằng lệnh -C build.
rem Ninja sẽ gọi trình biên dịch chéo arm-none-eabi-gcc để dịch mã nguồn.
rem Sản phẩm cuối cùng của giai đoạn này là file mã máy nhị phân (.bin).
echo STEP 3: COMPILING FIRMWARE WITH NINJA
ninja -C build
if %errorlevel% neq 0 (
    echo [ERROR] Compilation failed!
    pause
    exit /b %errorlevel%
)

rem ----------------------------------------------------------------------------
rem ĐOẠN TỰ ĐỘNG DÒ FILE VÀ ĐỒNG BỘ THÀNH APP_FIRMWARE.BIN
rem Vòng lặp quét qua thư mục build/ để tìm bất kỳ file .bin nào vừa được sinh ra
rem (ví dụ: file stm32f103_aht20_baremetal.bin của dự án I2C).
rem Sau khi tìm thấy, tiến hành nhân bản và đổi tên thành app_firmware.bin 
rem nhằm thỏa mãn ràng buộc file nạp của đề bài mà không cần sửa file CMakeLists.txt.
rem ----------------------------------------------------------------------------
set "FOUND_BIN="
for %%F in (build\*.bin) do (
    set "FOUND_BIN=%%F"
)

if defined FOUND_BIN (
    if /i not "!FOUND_BIN!"=="build\app_firmware.bin" (
        copy /y "!FOUND_BIN!" "build\app_firmware.bin" >nul
    )
) else (
    echo [ERROR] No .bin file generated by Ninja!
    pause
    exit /b 1
)
echo.

:: =============================================================================
:: STEP 4: FLASHING FIRMWARE TO TARGET MCU
:: =============================================================================
rem Bước này sử dụng công cụ nạp chính thức STM32_Programmer_CLI của ST.
rem -c port=SWD: Chỉ định kết nối với mạch nạp ST-Link thông qua giao thức SWD.
rem -w build/app_firmware.bin 0x08000000: Ghi file nhị phân vào đầu vùng nhớ Flash.
rem -v: Kích hoạt tính năng xác thực dữ liệu (Verify) sau khi ghi xong.
rem -rst: Phát tín hiệu Reset phần cứng để chip tự động thực thi code ngay lập tức.
echo STEP 4: FLASHING FIRMWARE TO TARGET MCU
STM32_Programmer_CLI -c port=SWD -w build/app_firmware.bin 0x08000000 -v -rst
if %errorlevel% neq 0 (
    echo [ERROR] Flashing failed! Please check ST-Link connection.
    pause
    exit /b %errorlevel%
)

echo.
echo ===================================================
echo [SUCCESS] Congratulations! System running smoothly.
echo ===================================================
pause